subarch: amd64
target: stage2
version_stamp: hardened-openrc-oubliette
rel_type: hardened
profile: default/linux/amd64/17.1/hardened
source_subpath: hardened/stage1-amd64-hardened-openrc-oubliette
compression_mode: pixz
portage_confdir: /opt/oubliette-releng/releases/portage/stages
portage_prefix: releng
snapshot_treeish: master
repos: /var/lib/layman/oubliette
